"""Read-only exposure contract tests for workflow policy artifacts.

These tests verify that the existing review evidence helper exposes
canonical workflow policy artifacts in a stable read-only shape, using
the full proof-of-work package generated by existing helpers. No API
endpoints, Mission Control UI, dispatcher integration, or runtime behavior.

This is a tests-only patch. No runtime behavior is added or modified.
"""

from __future__ import annotations

import importlib.util
import io
import json
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest import mock

from agent_taskflow.api.review import build_artifact_file_summaries
from agent_taskflow.workflow_policy_artifacts import (
    WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME,
    WORKFLOW_POLICY_ARTIFACT_INDEX_TYPE,
    WORKFLOW_POLICY_ARTIFACT_INDEX_VERSION,
    WORKFLOW_POLICY_PACKAGE_TYPE,
    WORKFLOW_POLICY_REVIEW_KIND,
    WORKFLOW_POLICY_SUMMARY_ARTIFACT_TYPE,
    WORKFLOW_POLICY_SUMMARY_FILENAME,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "run_workflow_policy_pow_package_smoke.py"
EXAMPLE_POLICY = REPO_ROOT / "examples" / "workflow-policy.example.json"


# ----------------------------------------------------------------------
# Package generator using existing helper
# ----------------------------------------------------------------------


def _load_smoke_module():
    spec = importlib.util.spec_from_file_location(
        "run_workflow_policy_pow_package_smoke",
        SCRIPT_PATH,
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _generate_package(
    artifact_dir: Path | None = None,
) -> tuple[Path, Path]:
    """Generate a full workflow policy proof-of-work package.

    Returns (artifact_dir, index_path, summary_path).
    """
    module = _load_smoke_module()
    stdout = io.StringIO()
    argv = []
    if artifact_dir is not None:
        argv.extend(["--artifact-dir", str(artifact_dir)])
    with redirect_stdout(stdout):
        exit_code = module.main(argv)
    if exit_code != 0:
        raise RuntimeError(f"package generation failed: {stdout.getvalue()}")
    if artifact_dir is None:
        for line in stdout.getvalue().splitlines():
            if line.startswith("artifact dir: "):
                artifact_dir = Path(line.removeprefix("artifact dir: "))
                break
        assert artifact_dir is not None
    index_path = artifact_dir / WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME
    summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
    return artifact_dir, index_path, summary_path


# ----------------------------------------------------------------------
# Tests: existing review evidence fields
# ----------------------------------------------------------------------


class ExistingFieldsExposureTests(unittest.TestCase):
    """Verify the review evidence helper exposes existing fields only."""

    def test_workflow_policy_summary_exposes_name(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            self.assertIn(WORKFLOW_POLICY_SUMMARY_FILENAME, by_name)
            entry = by_name[WORKFLOW_POLICY_SUMMARY_FILENAME]
            self.assertIn("name", entry)
            self.assertEqual(entry["name"], WORKFLOW_POLICY_SUMMARY_FILENAME)

    def test_workflow_policy_summary_exposes_kind(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_SUMMARY_FILENAME]
            self.assertIn("kind", entry)
            self.assertEqual(entry["kind"], WORKFLOW_POLICY_REVIEW_KIND)

    def test_workflow_policy_summary_exposes_size_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_SUMMARY_FILENAME]
            self.assertIn("size_bytes", entry)
            self.assertGreater(entry["size_bytes"], 0)

    def test_workflow_policy_summary_is_not_validator_log(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_SUMMARY_FILENAME]
            self.assertFalse(entry["is_validator_log"])

    def test_workflow_policy_summary_is_not_executor_log(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_SUMMARY_FILENAME]
            self.assertFalse(entry["is_executor_log"])

    def test_workflow_policy_summary_is_not_mission_contract(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_SUMMARY_FILENAME]
            self.assertFalse(entry["is_mission_contract"])

    def test_artifact_index_exposes_name(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            self.assertIn(WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME, by_name)
            entry = by_name[WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME]
            self.assertIn("name", entry)
            self.assertEqual(entry["name"], WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME)

    def test_artifact_index_exposes_kind(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME]
            self.assertIn("kind", entry)
            self.assertEqual(entry["kind"], WORKFLOW_POLICY_REVIEW_KIND)

    def test_artifact_index_exposes_size_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME]
            self.assertIn("size_bytes", entry)
            self.assertGreater(entry["size_bytes"], 0)

    def test_artifact_index_is_not_validator_log(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME]
            self.assertFalse(entry["is_validator_log"])

    def test_artifact_index_is_not_executor_log(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME]
            self.assertFalse(entry["is_executor_log"])

    def test_artifact_index_is_not_mission_contract(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            by_name = {r["name"]: r for r in results}
            entry = by_name[WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME]
            self.assertFalse(entry["is_mission_contract"])


# ----------------------------------------------------------------------
# Tests: artifact contents remain parseable
# ----------------------------------------------------------------------


class ArtifactContentsContractTests(unittest.TestCase):
    """Verify artifact file contents are independently parseable and correct."""

    def test_workflow_policy_summary_has_validation_status_passed(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertEqual(summary["validation_status"], "passed")

    def test_workflow_policy_summary_has_artifact_type_workflow_policy_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertEqual(
                summary["artifact_type"], WORKFLOW_POLICY_SUMMARY_ARTIFACT_TYPE
            )

    def test_artifact_index_has_package_type_workflow_policy_proof_of_work(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            index_path = artifact_dir / WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME
            index = json.loads(index_path.read_text(encoding="utf-8"))
            self.assertEqual(index["package_type"], WORKFLOW_POLICY_PACKAGE_TYPE)

    def test_artifact_index_has_artifact_index_version_0_1(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            index_path = artifact_dir / WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME
            index = json.loads(index_path.read_text(encoding="utf-8"))
            self.assertEqual(index["artifact_index_version"], WORKFLOW_POLICY_ARTIFACT_INDEX_VERSION)

    def test_artifact_index_references_workflow_policy_summary_json(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            index_path = artifact_dir / WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME
            index = json.loads(index_path.read_text(encoding="utf-8"))
            summary_entries = [
                a for a in index["artifacts"]
                if isinstance(a, dict) and a.get("name") == "workflow_policy_summary"
            ]
            self.assertEqual(len(summary_entries), 1)
            entry = summary_entries[0]
            self.assertEqual(entry["path"], WORKFLOW_POLICY_SUMMARY_FILENAME)
            self.assertEqual(
                entry["artifact_type"], WORKFLOW_POLICY_SUMMARY_ARTIFACT_TYPE
            )
            self.assertIs(entry["required"], True)

    def test_workflow_policy_summary_has_validation_errors_field(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertIn("validation_errors", summary)
            self.assertIsInstance(summary["validation_errors"], list)

    def test_workflow_policy_summary_has_validation_warnings_field(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertIn("validation_warnings", summary)
            self.assertIsInstance(summary["validation_warnings"], list)

    def test_workflow_policy_summary_has_required_validators(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertIn("required_validators", summary)
            self.assertIsInstance(summary["required_validators"], list)

    def test_workflow_policy_summary_has_allowed_executors(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertIn("allowed_executors", summary)
            self.assertIsInstance(summary["allowed_executors"], list)

    def test_workflow_policy_summary_has_forbidden_actions(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertIn("forbidden_actions", summary)
            self.assertIsInstance(summary["forbidden_actions"], list)


# ----------------------------------------------------------------------
# Tests: read-only semantics
# ----------------------------------------------------------------------


class ReadOnlySemanticsTests(unittest.TestCase):
    """Verify the review evidence helper does not mutate artifact files."""

    def test_build_artifact_file_summaries_does_not_mutate_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            summary_path = artifact_dir / WORKFLOW_POLICY_SUMMARY_FILENAME
            index_path = artifact_dir / WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME
            before_summary = summary_path.read_bytes()
            before_index = index_path.read_bytes()

            results = build_artifact_file_summaries(artifact_dir)
            after_summary = summary_path.read_bytes()
            after_index = index_path.read_bytes()

            self.assertEqual(len(results), 2)
            self.assertEqual(before_summary, after_summary)
            self.assertEqual(before_index, after_index)

    def test_build_artifact_file_summaries_does_not_create_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            before_files = set(artifact_dir.iterdir())

            build_artifact_file_summaries(artifact_dir)

            after_files = set(artifact_dir.iterdir())
            self.assertEqual(before_files, after_files)

    def test_build_artifact_file_summaries_does_not_call_dispatcher(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            with mock.patch("agent_taskflow.dispatcher.Dispatcher") as mock_disp:
                build_artifact_file_summaries(artifact_dir)
            mock_disp.assert_not_called()

    def test_build_artifact_file_summaries_does_not_call_executor(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            with mock.patch("subprocess.run") as mock_run:
                build_artifact_file_summaries(artifact_dir)
            mock_run.assert_not_called()

    def test_build_artifact_file_summaries_does_not_call_validator_registry(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            # The helper never calls validators; this is a no-op guard.
            from agent_taskflow.validators import get_validator
            with mock.patch("agent_taskflow.validators.get_validator") as mock_gv:
                build_artifact_file_summaries(artifact_dir)
            mock_gv.assert_not_called()

    def test_package_generation_does_not_call_dispatcher(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            with mock.patch("agent_taskflow.dispatcher.Dispatcher") as mock_disp:
                _generate_package(artifact_dir)
            mock_disp.assert_not_called()

    def test_package_generation_does_not_call_executor(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            with mock.patch("subprocess.run") as mock_run:
                _generate_package(artifact_dir)
            mock_run.assert_not_called()


# ----------------------------------------------------------------------
# Tests: non-goals (no approval/merge/push/cleanup artifacts)
# ----------------------------------------------------------------------


class NonGoalsVerificationTests(unittest.TestCase):
    """Verify no approval, merge, push, or cleanup artifacts are created."""

    def test_no_approval_artifact_created(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            files = {p.name for p in artifact_dir.iterdir()}
            for name in files:
                self.assertNotIn("approve", name.lower())
                self.assertNotIn("approval", name.lower())

    def test_no_merge_artifact_created(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            files = {p.name for p in artifact_dir.iterdir()}
            for name in files:
                self.assertNotIn("merge", name.lower())

    def test_no_push_artifact_created(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            files = {p.name for p in artifact_dir.iterdir()}
            for name in files:
                self.assertNotIn("push", name.lower())

    def test_no_cleanup_artifact_created(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            files = {p.name for p in artifact_dir.iterdir()}
            for name in files:
                self.assertNotIn("cleanup", name.lower())

    def test_no_delete_branch_artifact_created(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            files = {p.name for p in artifact_dir.iterdir()}
            for name in files:
                self.assertNotIn("delete_branch", name.lower())
                self.assertNotIn("delete-worktree", name.lower())

    def test_no_pr_artifact_created(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            files = {p.name for p in artifact_dir.iterdir()}
            for name in files:
                self.assertNotIn("pull_request", name.lower())
                self.assertNotIn("_pr_", name.lower())

    def test_review_evidence_helper_does_not_write_approval_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            before = {p.name for p in artifact_dir.iterdir()}
            build_artifact_file_summaries(artifact_dir)
            after = {p.name for p in artifact_dir.iterdir()}
            self.assertEqual(before, after)

    def test_workflow_policy_artifacts_not_misclassified_as_write_actions(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            artifact_dir = Path(tmp)
            _generate_package(artifact_dir)
            results = build_artifact_file_summaries(artifact_dir)
            for entry in results:
                name = entry["name"]
                # None of the canonical workflow policy artifacts should suggest
                # write action capability.
                self.assertFalse(
                    name.endswith(".sh") and any(
                        kw in name.lower()
                        for kw in ("merge", "push", "cleanup", "approve", "delete")
                    ),
                    f"{name!r} should not be present in workflow policy package",
                )


# ----------------------------------------------------------------------
# Tests: constants alignment
# ----------------------------------------------------------------------


class ConstantsAlignmentTests(unittest.TestCase):
    """Verify test uses canonical constants, not hardcoded strings."""

    def test_workflow_policy_review_kind_value(self) -> None:
        self.assertEqual(WORKFLOW_POLICY_REVIEW_KIND, "workflow_policy")

    def test_workflow_policy_summary_artifact_type_value(self) -> None:
        self.assertEqual(WORKFLOW_POLICY_SUMMARY_ARTIFACT_TYPE, "workflow_policy_summary")

    def test_workflow_policy_artifact_index_type_value(self) -> None:
        self.assertEqual(WORKFLOW_POLICY_ARTIFACT_INDEX_TYPE, "artifact_index")

    def test_workflow_policy_package_type_value(self) -> None:
        self.assertEqual(WORKFLOW_POLICY_PACKAGE_TYPE, "workflow_policy_proof_of_work")

    def test_workflow_policy_artifact_index_version_value(self) -> None:
        self.assertEqual(WORKFLOW_POLICY_ARTIFACT_INDEX_VERSION, "0.1")

    def test_workflow_policy_summary_filename_value(self) -> None:
        self.assertEqual(WORKFLOW_POLICY_SUMMARY_FILENAME, "workflow_policy_summary.json")

    def test_workflow_policy_artifact_index_filename_value(self) -> None:
        self.assertEqual(WORKFLOW_POLICY_ARTIFACT_INDEX_FILENAME, "artifact_index.json")


if __name__ == "__main__":
    unittest.main()